### ISSUE TITLE
Elixir 1.6.2 causes this plugin to ignore .formatter.exs

### ISSUE THREAD

**Issue by doughsay** [rgreenjr/atom-elixir-formatter#17] opened 2018-03-02 01:16 UTC
After upgrading to Elixir 1.6.2, it appears my `.formatter.exs` file is being ignored.

I'm working inside an umbrella application, but putting the formatter settings into the top level `.formatter.exs` as well as the individual app `.formatter.exs` files makes no difference.

Switching back to 1.6.1 makes it work again.  Also, running `mix format` from the umbrella app folder works as expected with 1.6.2.

**Comment by rgreenjr** [comment] 2018-03-02 14:45
Thanks for the bug report. I just upgraded to Elixir v1.6.2 and I'm getting the same buggy behavior. I'll set aside time this weekend to try to figure what's going on.

**Comment by rgreenjr** [comment] 2018-03-02 21:03
I did some investigating and it looks like this is a regression in Elixir v1.6.2. I've filed an [issue](https://github.com/elixir-lang/elixir/issues/7411) to let the core team know. Hopefully it will be fixed in the next Elixir release. I'll keep this issue open until it's resolved.

**Comment by rgreenjr** [comment] 2018-03-03 01:14
Good news. José has already [committed a fix](https://github.com/elixir-lang/elixir/commit/755639f538639837d55660cde30e577d1764f3c5) for this issue.

**Comment by doughsay** [comment] 2018-03-05 18:09
Thanks for looking into it!  Looking forward to the patch.  For now I'll stick with 1.6.1 for my formatting needs.

**Comment by rgreenjr** [comment] 2018-03-09 14:46
Closing now that the issue is fixed in Elixir v1.6.3.

**Closed by rgreenjr** 2018-03-09 14:46 UTC
