### ISSUE TITLE
line_length ignored

### ISSUE THREAD

**Issue by marinakr** [rgreenjr/atom-elixir-formatter#25] opened 2019-01-10 16:58 UTC
I have an umbrella project with root file .formatter.exs `line_length: 120` but  formatter anyway  ignore this file + preffered_line_length in atom settings is 120
Max length always is 100

**Comment by rgreenjr** [comment] 2019-01-10 22:37
Hi @marinakr – I'm having trouble reproducing this issue. I created a project with a `.formatter.exs` file in the root directory with `line_length: 120` and the formatter is breaking lines correctly.

Can you post your `formatter.exs` file?

**Comment by marinakr** [comment] 2019-01-11 23:52
This issue was fixing by adding line 'line_length' to formatter file in the app .formatter:
```
apps/core/.formatter.exs
@@ -1,3 +1,4 @@
[
  - inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"]
  + inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  + line_length: 120
]
```
root formatter file: 
```
[
  inputs: ["mix.exs", "mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 120
]
```

**Comment by marinakr** [comment] 2019-01-12 19:40
Why did you close it? Formatter shoul work with root file, not formatter in apps/app_name. Issue is reproduced on OSX

**Comment by rgreenjr** [comment] 2019-01-12 20:02
I was confused when you closed the issue and reopened it without explaining why. I assumed you reopened it on accident, so I closed it. I also must have misunderstood your earlier comment.

Please post more details, including the directory structure of your project and which files are not being formatted correctly. Also, note that the formatter always uses the nearest `.formatter.exs` file when deciding how to format a file, so nested `.formatter.exs` files will override those higher up in the directory.

**Comment by marinakr** [comment] 2019-01-14 09:49
https://github.com/edenlabllc/mpi.api - umbrella application. In PR   https://github.com/edenlabllc/mpi.api/pull/170/commits/c9b2e0c3be02d6b488ba8e8d0d31fa2dc12aa600 -  file "apps/core/.formatter.exs" - line_length was added. Before it file person_api.ex had lines that was formatted to new lines, and as I noticed it formatted them after 100 characters in line. Root .formatter.exs with line_length was 120 ignored.

**Comment by rgreenjr** [comment] 2019-01-15 02:31
Ok, now I understand what's going on.

The atom-elixir-formatter uses the nearest `.formatter.exs` file when formatting a file. The nearest formatter file to `apps/core/lib/application.ex` is `apps/core/.formatter.exs`. Because it did not originally specify a `line_length` value, the formatter used the default value.

If you want, you can delete `apps/core/.formatter.exs`. It is configured the same as the root `.formatter` file (except for the unneeded duplication of `"mix.exs"`).

**Comment by rgreenjr** [comment] 2020-01-25 20:14
I'm closing this issue as resolved since there was no response for 12 months.

**Closed by rgreenjr** 2020-01-25 20:14 UTC
