### ISSUE TITLE
Farmatter fails when running format on save on config files

### ISSUE THREAD

**Issue by lukaszsamson** [rgreenjr/atom-elixir-formatter#5] opened 2017-10-12 13:33 UTC
Reproduction:
1. Introduce a syntax error in config & format on save. This should result in error like
```
mix format failed for file: /var/folders/5t/z9kkxlhn4w769jqmn00xqqkw0000gn/T/tmp-55821Dfj8OLtzEFgZ
** (SyntaxError) /var/folders/5t/z9kkxlhn4w769jqmn00xqqkw0000gn/T/tmp-55821Dfj8OLtzEFgZ:85: syntax error before: env
    (elixir) lib/code.ex:370: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:148: Mix.Tasks.Format.format_file/4
    (elixir) lib/enum.ex:1900: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/format.ex:84: Mix.Tasks.Format.run/1
    (mix) lib/mix/task.ex:315: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```
2. Fix the error & format on save

Expected:
File formatted

Current:
```
** (Mix.Config.LoadError) could not load config apps/my_app/config/dev.exs
    ** (SyntaxError) apps/my_app/config/dev.exs:85: syntax error before: env
    (elixir) lib/code.ex:176: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1900: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
```

The issue does not happen when using format from command line nor keybinding.
The issue seems to affect only config files.

**Comment by rgreenjr** [comment] 2017-10-12 14:31
I think here's what is happening:

1. A syntax error is introduced to the config file, so format on save generates an error (e.g. ```missing terminator: ]```) but the file is saved successfully.
2. When the error is fixed and the file saved again, the formatter is run before save, which means the code formatter still sees the broken config file on the file system and issues a warning (e.g. ```could not load config config/dev.exs```) but the file is saved successfully.
3. Subsequent saves/formats work fine.

I'm not sure there's a working around for this. I tried to reproduce the problem with other files, but it only occurs with config files (which led to my conclusion above). I think about the problem some more, but this may just be a rare corner case.

**Comment by rgreenjr** [comment] 2017-10-12 14:31
Excellent bug report however! 👍

**Comment by lukaszsamson** [comment] 2017-10-16 21:19
@rgreenjr that's exactly what is happening. I can think of a three possible workarounds for this issue. The first would be to not pass cwd option to the formatter command (or set it to the temp dir) so the mix process won't try to load project's config. The second is to save first and then do the formatting in onDidSave callback and finally save again after formatting. The third is to format in-place without copying to temp dir in onDidSave.

**Comment by rgreenjr** [comment] 2017-10-16 22:34
We have to pass the `cwd` option so the user's `.formatter.exs` file will be accessible to the `mix format` task. Formatting after the `onDidSave` callback and then saving sounds like it would result in an infinite loop, right? I don't totally understand the third option. Can you give a little more detail? 

Also, take note that the current use of temporary files will be removed soon. I was able to persuade José yesterday to add support for formatting via stdin/stdout, so it's no longer needed.

Thanks.

**Comment by rgreenjr** [comment] 2017-11-02 14:59
I'm going to close this issue since I don't see a way to resolve the circular dependency at the core of this problem. But I'm happy to reopen it if a solution is devised.

**Closed by rgreenjr** 2017-11-02 14:59 UTC
